import { describe, test, expect, beforeAll } from 'vitest';
import request from 'supertest';
import { fileURLToPath } from 'url';
import path from 'path';
import { app } from '../../server/index.js';
import { writeDb, readDb, DbStudentPrintHistory } from '../../server/db.js';
import { executeRetentionPurge } from '../../server/storage.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

describe('Phase 1: Lifetime Student Print History Suite', () => {
  let studentAToken: string;
  let studentBToken: string;
  let adminToken: string;

  const EIGHT_DAYS_AGO = new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString();
  const TWO_DAYS_AGO = new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString();

  beforeAll(async () => {
    // 1. Authenticate Student A
    const resA = await request(app)
      .post('/api/auth/google')
      .send({ idToken: 'mock_token_alice' });
    expect(resA.status).toBe(200);
    studentAToken = resA.body.sessionToken;

    // 2. Authenticate Student B
    const resB = await request(app)
      .post('/api/auth/google')
      .send({ idToken: 'mock_token_bob' });
    expect(resB.status).toBe(200);
    studentBToken = resB.body.sessionToken;

    // 3. Admin login for shop
    const adminRes = await request(app)
      .post('/api/auth/login')
      .send({ shopId: 'tjohn_print', username: 'tjohn_admin', password: 'password123' });
    adminToken = adminRes.body.token;

    // Get actual student IDs generated by google auth
    const meA = await request(app)
      .get('/api/me')
      .set('Authorization', `Bearer ${studentAToken}`);
    const actualStudentAId = meA.body.id;

    const meB = await request(app)
      .get('/api/me')
      .set('Authorization', `Bearer ${studentBToken}`);
    const actualStudentBId = meB.body.id;

    // Seed test history across multiple print centers
    const db = readDb();
    db.studentPrintHistory = [
      {
        id: 'hist-alice-job-001',
        orderId: 'order-alice-001',
        jobId: 'job-alice-001',
        orderToken: 'TK-ALICE-1',
        jobToken: 'TK-ALICE-1',
        studentId: actualStudentAId,
        shopId: 'tjohn_print',
        shopName: 'TJohn Print Center',
        fileName: 'TJohn_Assignment.pdf',
        fileSize: 2048,
        pageCount: 10,
        copies: 1,
        printMode: 'mono',
        printType: 'bw',
        sides: 'single',
        paperSize: 'A4',
        chargedAmount: 20,
        status: 'completed',
        createdAt: EIGHT_DAYS_AGO,
        completedAt: EIGHT_DAYS_AGO
      },
      {
        id: 'hist-alice-job-002',
        orderId: 'order-alice-002',
        jobId: 'job-alice-002',
        orderToken: 'TK-ALICE-2',
        jobToken: 'TK-ALICE-2',
        studentId: actualStudentAId,
        shopId: 'alliance_print',
        shopName: 'Alliance Print Center',
        fileName: 'Alliance_Project.pdf',
        fileSize: 4096,
        pageCount: 5,
        copies: 2,
        printMode: 'color',
        printType: 'color',
        sides: 'double',
        paperSize: 'A4',
        chargedAmount: 50,
        status: 'completed',
        createdAt: TWO_DAYS_AGO,
        completedAt: TWO_DAYS_AGO
      },
      {
        id: 'hist-alice-job-003',
        orderId: 'order-alice-003',
        jobId: 'job-alice-003',
        orderToken: 'TK-ALICE-3',
        jobToken: 'TK-ALICE-3',
        studentId: actualStudentAId,
        shopId: 'science_print',
        shopName: 'Science Print Center',
        fileName: 'Science_Thesis.pdf',
        fileSize: 8192,
        pageCount: 25,
        copies: 1,
        printMode: 'mono',
        printType: 'bw',
        sides: 'double',
        paperSize: 'A4',
        chargedAmount: 75,
        status: 'pending_approval',
        createdAt: new Date().toISOString()
      },
      {
        id: 'hist-bob-job-001',
        orderId: 'order-bob-001',
        jobId: 'job-bob-001',
        orderToken: 'TK-BOB-99',
        jobToken: 'TK-BOB-99',
        studentId: actualStudentBId,
        shopId: 'tjohn_print',
        shopName: 'TJohn Print Center',
        fileName: 'Bob_Confidential.pdf',
        fileSize: 1024,
        pageCount: 2,
        copies: 1,
        printMode: 'mono',
        printType: 'bw',
        sides: 'single',
        paperSize: 'A4',
        chargedAmount: 4,
        status: 'completed',
        createdAt: TWO_DAYS_AGO,
        completedAt: TWO_DAYS_AGO
      }
    ];

    // Seed matching operational jobs/orders (some 8 days old for retention test)
    db.orders = [
      {
        id: 'order-alice-001',
        token: 'TK-ALICE-1',
        studentId: actualStudentAId,
        studentName: 'Alice',
        studentEmail: 'alice@university.edu',
        shopId: 'tjohn_print',
        status: 'completed',
        totalChargedAmount: 20,
        jobIds: ['job-alice-001'],
        createdAt: EIGHT_DAYS_AGO
      }
    ];
    db.jobs = [
      {
        id: 'job-alice-001',
        token: 'TK-ALICE-1',
        orderId: 'order-alice-001',
        fileName: 'TJohn_Assignment.pdf',
        fileSize: 2048,
        pageCount: 10,
        copies: 1,
        printMode: 'mono',
        printType: 'bw',
        sides: 'single',
        status: 'completed',
        chargedAmount: 20,
        studentName: 'Alice',
        studentEmail: 'alice@university.edu',
        studentId: actualStudentAId,
        createdAt: EIGHT_DAYS_AGO,
        serverFilePath: '/uploads/old_alice_doc.pdf',
        shopId: 'tjohn_print',
        timeline: []
      }
    ];

    writeDb(db);
  });

  // TEST 1: Student can retrieve their own history
  test('TEST 1: Authenticated Student A can retrieve their own history', async () => {
    const res = await request(app)
      .get('/api/student/history')
      .set('Authorization', `Bearer ${studentAToken}`);

    expect(res.status).toBe(200);
    expect(Array.isArray(res.body)).toBe(true);
    expect(res.body.length).toBe(3); // Alice has 3 jobs

    const tokens = res.body.map((item: any) => item.orderToken);
    expect(tokens).toContain('TK-ALICE-1');
    expect(tokens).toContain('TK-ALICE-2');
    expect(tokens).toContain('TK-ALICE-3');
  });

  // TEST 2: Student A cannot retrieve Student B's history (strict isolation)
  test('TEST 2: Student A NEVER receives Student B records (Zero cross-student leakage)', async () => {
    const resA = await request(app)
      .get('/api/student/history')
      .set('Authorization', `Bearer ${studentAToken}`);

    expect(resA.status).toBe(200);
    const hasBobRecord = resA.body.some((item: any) => 
      item.orderToken === 'TK-BOB-99' || 
      item.fileName === 'Bob_Confidential.pdf'
    );
    expect(hasBobRecord).toBe(false);

    // Student B requests history
    const resB = await request(app)
      .get('/api/student/history')
      .set('Authorization', `Bearer ${studentBToken}`);

    expect(resB.status).toBe(200);
    expect(resB.body.length).toBe(1);
    expect(resB.body[0].orderToken).toBe('TK-BOB-99');
    expect(resB.body[0].fileName).toBe('Bob_Confidential.pdf');
  });

  // TEST 3: History works across ALL print shops
  test('TEST 3: History consolidates jobs from all print centers (TJohn, Alliance, Science)', async () => {
    const res = await request(app)
      .get('/api/student/history')
      .set('Authorization', `Bearer ${studentAToken}`);

    expect(res.status).toBe(200);
    const shopNames = res.body.map((item: any) => item.shopName);
    expect(shopNames).toContain('TJohn Print Center');
    expect(shopNames).toContain('Alliance Print Center');
    expect(shopNames).toContain('Science Print Center');
  });

  // TEST 4: History remains available after operational records are purged (7-day retention)
  test('TEST 4: Lifetime history SURVIVES 7-day operational purge', async () => {
    // Run the 7-day retention purge
    await executeRetentionPurge(7);

    const db = readDb();
    // Operational job from 8 days ago must be purged from jobs and orders tables
    const operationalJobExists = db.jobs.some(j => j.id === 'job-alice-001');
    const operationalOrderExists = (db.orders || []).some(o => o.id === 'order-alice-001');
    expect(operationalJobExists).toBe(false);
    expect(operationalOrderExists).toBe(false);

    // BUT student history ledger MUST still retain the record!
    const res = await request(app)
      .get('/api/student/history')
      .set('Authorization', `Bearer ${studentAToken}`);

    expect(res.status).toBe(200);
    const purgedJobInHistory = res.body.find((item: any) => item.jobId === 'job-alice-001');
    expect(purgedJobInHistory).toBeDefined();
    expect(purgedJobInHistory.orderToken).toBe('TK-ALICE-1');
    expect(purgedJobInHistory.fileName).toBe('TJohn_Assignment.pdf');
    expect(purgedJobInHistory.status).toBe('completed');
  });

  // TEST 5: History contains metadata ONLY (no storage paths, signed URLs, or student PII)
  test('TEST 5: History response strictly omits serverFilePath, originalFilePath, download URLs, and redundant student PII', async () => {
    const res = await request(app)
      .get('/api/student/history')
      .set('Authorization', `Bearer ${studentAToken}`);

    expect(res.status).toBe(200);
    for (const record of res.body) {
      expect(record.serverFilePath).toBeUndefined();
      expect(record.server_file_path).toBeUndefined();
      expect(record.originalFilePath).toBeUndefined();
      expect(record.original_file_path).toBeUndefined();
      expect(record.downloadUrl).toBeUndefined();
      expect(record.signedUrl).toBeUndefined();
      expect(record.studentName).toBeUndefined();
      expect(record.student_name).toBeUndefined();
      expect(record.studentEmail).toBeUndefined();
      expect(record.student_email).toBeUndefined();

      // Ensure safe student metadata exists
      expect(record.orderToken).toBeDefined();
      expect(record.fileName).toBeDefined();
      expect(record.chargedAmount).toBeDefined();
      expect(record.shopName).toBeDefined();
      expect(record.pageCount).toBeGreaterThan(0);
      expect(record.copies).toBeGreaterThan(0);
    }
  });

  // TEST 6: Duplicate history creation is prevented (Idempotency)
  test('TEST 6: Idempotent history insertion prevents duplicate records for same job', async () => {
    const db = readDb();
    const beforeCount = (db.studentPrintHistory || []).length;

    // Simulate duplicate insertion of same job
    const duplicateRecord: DbStudentPrintHistory = {
      id: 'hist-alice-job-002-dup',
      orderId: 'order-alice-002',
      jobId: 'job-alice-002', // SAME jobId
      orderToken: 'TK-ALICE-2',
      studentId: db.studentPrintHistory!.find(h => h.jobId === 'job-alice-002')!.studentId,
      shopId: 'alliance_print',
      shopName: 'Alliance Print Center',
      fileName: 'Alliance_Project.pdf',
      fileSize: 4096,
      pageCount: 5,
      copies: 2,
      printMode: 'color',
      sides: 'double',
      chargedAmount: 50,
      status: 'completed',
      createdAt: TWO_DAYS_AGO
    };

    // Use readDb / writeDb pattern with deduplication
    const idx = db.studentPrintHistory!.findIndex(h => h.jobId === duplicateRecord.jobId);
    if (idx >= 0) {
      db.studentPrintHistory![idx] = duplicateRecord;
    } else {
      db.studentPrintHistory!.push(duplicateRecord);
    }
    writeDb(db);

    const afterDb = readDb();
    expect(afterDb.studentPrintHistory!.length).toBe(beforeCount); // No duplicate row created
  });

  // TEST 7: Empty history returns [] with 200 OK
  test('TEST 7: New student with zero prints receives empty history []', async () => {
    const newStudentRes = await request(app)
      .post('/api/auth/google')
      .send({ idToken: 'mock_token_brandnewstudent' });
    const newToken = newStudentRes.body.sessionToken;

    const res = await request(app)
      .get('/api/student/history')
      .set('Authorization', `Bearer ${newToken}`);

    expect(res.status).toBe(200);
    expect(res.body).toEqual([]);
  });

  // TEST 8: Pagination (limit & offset) works accurately
  test('TEST 8: Pagination parameters (limit and offset) slice history records correctly', async () => {
    const resLimit1 = await request(app)
      .get('/api/student/history?limit=1')
      .set('Authorization', `Bearer ${studentAToken}`);

    expect(resLimit1.status).toBe(200);
    expect(resLimit1.body.length).toBe(1);

    const resOffset1 = await request(app)
      .get('/api/student/history?limit=1&offset=1')
      .set('Authorization', `Bearer ${studentAToken}`);

    expect(resOffset1.status).toBe(200);
    expect(resOffset1.body.length).toBe(1);
    expect(resOffset1.body[0].id).not.toBe(resLimit1.body[0].id);
  });

  // TEST 9: Unauthenticated request is rejected with 401
  test('TEST 9: Unauthenticated request to /api/student/history returns 401 Unauthorized', async () => {
    const res = await request(app).get('/api/student/history');
    expect(res.status).toBe(401);
  });
});
